version: "3.7"
services:
  app:
    container_name: openinterpreter
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../work:/work
    tty: true


